<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy | Tech Cargo Hub</title>
    <link rel="icon" type="image/png" href="https://www.techcargohub.com/assets/images/second-logo.png">
    <link rel="stylesheet" href="{{ asset('assets/css/tailwind.css') }}">
</head>
<body style="background-color: #fff; color: #333; font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 0;">
  
  @include('partials.header')

  <main style="max-width: 900px; margin: 40px auto; padding: 0 20px;">
    <h1 style="text-align: center; margin-bottom: 30px; font-size: 2.5rem; font-weight: bold;">Privacy Policy</h1>

    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
    <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

    <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Interpretation and Definitions</h2>
    <h3 style="font-size: 1.4rem; font-weight: 600; margin-top: 1.5rem;">Interpretation</h3>
    <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.</p>

    <h3 style="font-size: 1.4rem; font-weight: 600; margin-top: 1.5rem;">Definitions</h3>
    <p>For the purposes of this Privacy Policy:</p>
    <ul style="margin-left: 2rem; margin-top: 1rem;">
      <li style="margin-bottom: 1rem;"><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
      <li style="margin-bottom: 1rem;"><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our") refers to Tech Cargo Hub (Pvt) Ltd, 112, Centre Road, Mattakkuliya, Colombo 15, Sri Lanka.</li>
      <li style="margin-bottom: 1rem;"><strong>Cookies</strong> are small files that are placed on Your device by a website, containing details of Your browsing history among its many uses.</li>
      <li style="margin-bottom: 1rem;"><strong>Country</strong> refers to Sri Lanka or your location.</li>
      <li style="margin-bottom: 1rem;"><strong>Device</strong> means any device that can access the Service such as a computer, cellphone or digital tablet.</li>
      <li style="margin-bottom: 1rem;"><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
      <li style="margin-bottom: 1rem;"><strong>Service</strong> refers to the Website.</li>
      <li style="margin-bottom: 1rem;"><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
      <li style="margin-bottom: 1rem;"><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
      <li style="margin-bottom: 1rem;"><strong>Website</strong> refers to Tech Cargo Hub (TCH), accessible from <a href="https://www.techcargohub.com" style="color: #10b981; text-decoration: underline;">www.techcargohub.com</a>.</li>
      <li style="margin-bottom: 1rem;"><strong>You</strong> means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service.</li>
    </ul>

    <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Collecting and Using Your Personal Data</h2>

    <h3 style="font-size: 1.4rem; font-weight: 600; margin-top: 1.5rem;">Types of Data Collected</h3>
    <h4 style="font-size: 1.2rem; font-weight: 600; margin-top: 1rem;">Personal Data</h4>
    <p>While using Our Service, We may ask You to provide certain personally identifiable information that can be used to contact or identify You. This may include, but is not limited to:</p>
    <ul style="margin-left: 2rem; margin-top: 1rem;">
      <li><strong>Email address.</strong></li>
      <li><strong>First name and last name.</strong></li>
      <li><strong>Phone number.</strong></li>
      <li><strong>Address, State, Province, ZIP/Postal code, City & Country.</strong></li>
      <li><strong>Usage Data.</strong></li>
    </ul>

    <h4 style="font-size: 1.2rem; font-weight: 600; margin-top: 1rem;">Usage Data</h4>
    <p>Usage Data is collected automatically when using the Service. It may include information such as Your IP address, browser type, browser version, pages visited, time and date of Your visit, and other diagnostic data.</p>

    <h4 style="font-size: 1.2rem; font-weight: 600; margin-top: 1rem;">Tracking Technologies and Cookies</h4>
    <p>We use Cookies and similar tracking technologies to track activity on Our Service and store certain information. These technologies include:</p>
    <ul style="margin-left: 2rem; margin-top: 1rem;">
      <li><strong>Cookies or Browser Cookies.</strong></li>
      <li><strong>Flash Cookies.</strong></li>
      <li><strong>Web Beacons.</strong></li>
    </ul>
    <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain when you go offline; Session Cookies are deleted when you close your browser.</p>

    <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Use of Your Personal Data</h2>
    <p>The Company may use Personal Data for purposes such as:</p>
    <ul style="margin-left: 2rem; margin-top: 1rem;">
      <li><strong>To provide and maintain our Service.</strong></li>
      <li><strong>To manage Your Account.</strong></li>
      <li><strong>For the performance of a contract.</strong></li>
      <li><strong>To contact You.</strong></li>
      <li><strong>To provide You with news.</strong></li>
      <li><strong>To manage Your requests.</strong></li>
      <li><strong>For business transfers.</strong></li>
      <li><strong>For other purposes.</strong></li>
    </ul>

    <p>We may share Your information in the following situations:</p>
    <ul style="margin-left: 2rem; margin-top: 1rem;">
      <li><strong>With Service Providers.</strong></li>
      <li><strong>For business transfers.</strong></li>
      <li><strong>With Affiliates.</strong></li>
      <li><strong>With business partners.</strong></li>
      <li><strong>With other users.</strong></li>
      <li><strong>With Your consent.</strong></li>
    </ul>

    <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Disclosure of Your Personal Data</h2>
    <h3 style="font-size: 1.4rem; font-weight: 600; margin-top: 1.5rem;">Other Legal Requirements</h3>
    <ul style="margin-left: 2rem; margin-top: 1rem;">
      <li><strong>Comply with a legal obligation.</strong></li>
      <li><strong>Protect and defend the rights or property of the Company.</strong></li>
      <li><strong>Prevent or investigate possible wrongdoing in connection with the Service.</strong></li>
      <li><strong>Protect against legal liability.</strong></li>
    </ul>

  </main>

  @include('partials.footer')

</body>
</html>
