<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy | Tech Cargo Hub</title>
    <link rel="icon" type="image/png" href="https://www.techcargohub.com/assets/images/second-logo.png">
    <link rel="stylesheet" href="{{ asset('assets/css/tailwind.css') }}">
</head>
<body style="background-color: #fff; color: #333; font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 0;">
  
  @include('partials.header')

  <main style="max-width: 900px; margin: 40px auto; padding: 0 20px;">
    <div>
      <h1 style="text-align: center; margin-bottom: 30px; font-size: 2.5rem; font-weight: bold;">Privacy Policy</h1>
      <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
      <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Template.</p>

      <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Interpretation and Definitions</h2>

      <h3 style="font-size: 1.4rem; font-weight: 600; margin-top: 1.5rem;">Interpretation</h3>
      <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

      <h3 style="font-size: 1.4rem; font-weight: 600; margin-top: 1.5rem;">Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul style="margin-left: 2rem; margin-top: 1rem;">
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Company</strong> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Tech Cargo Hub (Pvt) Ltd, 112, Centre Road, Mattakkuliya, Colombo 15, Sri Lanka.</li>
        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li><strong>Country</strong> refers to: Sri Lanka or your location.</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the Website.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>Website</strong> refers to Tech Cargo Hub (TCH), accessible from <a href="https://www.techcargohub.com" style="color: #10b981; text-decoration: underline;">www.techcargohub.com</a>.</li>
        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>

      <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Collecting and Using Your Personal Data</h2>

      <h3 style="font-size: 1.4rem; font-weight: 600; margin-top: 1.5rem;">Types of Data Collected</h3>

      <h3 style="font-size: 1.4rem; font-weight: 600; margin-top: 1rem;">Personal Data</h3>
      <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
      <ul style="margin-left: 2rem; margin-top: 1rem;">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City, & Country</li>
        <li>Usage Data</li>
      </ul>

      <h3 style="font-size: 1.4rem; font-weight: 600; margin-top: 1rem;">Usage Data</h3>
      <p>Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
      <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
      <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

      <h3 style="font-size: 1.4rem; font-weight: 600; margin-top: 1rem;">Tracking Technologies and Cookies</h3>
      <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
      <ul style="margin-left: 2rem; margin-top: 1rem;">
        <li>Cookies or Browser Cookies</li>
        <li>Flash Cookies</li>
        <li>Web Beacons</li>
      </ul>

      <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Use of Your Personal Data</h2>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul style="margin-left: 2rem; margin-top: 1rem;">
        <li>To provide and maintain our Service</li>
        <li>To manage Your Account</li>
        <li>For the performance of a contract</li>
        <li>To contact You</li>
        <li>To provide You with news</li>
        <li>To manage Your requests</li>
        <li>For business transfers</li>
        <li>For other purposes</li>
      </ul>

      <p>We may share Your personal information in the following situations:</p>
      <ul style="margin-left: 2rem; margin-top: 1rem;">
        <li>With Service Providers</li>
        <li>For business transfers</li>
        <li>With Affiliates</li>
        <li>With business partners</li>
        <li>With other users</li>
        <li>With Your consent</li>
      </ul>

      <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Retention of Your Personal Data</h2>
      <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. Usage Data is generally retained for a shorter period of time, except when legally required to retain longer.</p>

      <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Transfer of Your Personal Data</h2>
      <p>Your information, including Personal Data, is processed at the Company’s operating offices and in other locations where parties involved in the processing are located.</p>

      <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Disclosure of Your Personal Data</h2>
      <h3 style="font-size: 1.4rem; font-weight: 600; margin-top: 1.5rem;">Business Transactions</h3>
      <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before it becomes subject to a different Privacy Policy.</p>
      <h3 style="font-size: 1.4rem; font-weight: 600; margin-top: 1.5rem;">Law enforcement</h3>
      <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid public authority requests.</p>
      <h3 style="font-size: 1.4rem; font-weight: 600; margin-top: 1.5rem;">Other legal requirements</h3>
      <ul style="margin-left: 2rem; margin-top: 1rem;">
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect against legal liability</li>
      </ul>

      <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Security of Your Personal Data</h2>
      <p>The security of Your Personal Data is important to Us, but no method of transmission over the Internet or electronic storage is 100% secure.</p>

      <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Children’s Privacy</h2>
      <p>Our Service does not address anyone under the age of 13. If We become aware that We have collected Personal Data from anyone under 13 without parental consent, We remove that information.</p>

      <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Links to Other Websites</h2>
      <p>Our Service may contain links to third-party websites. We have no control over and assume no responsibility for the content, privacy policies or practices of third-party sites.</p>

      <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Changes to this Privacy Policy</h2>
      <p>We may update Our Privacy Policy from time to time. Updates will be posted on this page and, if applicable, notified by email or Service notice.</p>

      <h2 style="font-size: 1.8rem; font-weight: 600; margin-top: 2rem;">Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, You can contact us via email: <a href="mailto:service@techcargohub.com" style="color: #10b981; text-decoration: underline;">service@techcargohub.com</a></p>
    </div>
  </main>

  @include('partials.footer')

</body>
</html>
